version: "3"
services:
  web:
    container_name: population-of-prefecture-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app/
      - /app/node_modules
